countries = [
           'Namibia',
             'Nauru',
             'Nepal',
             'Netherlands',
             'New Zealand',
             'Nicaragua',
             'Niger',
             'Nigeria',
             'Norway',
             'Oman',
             'Pakistan',
             'Palau',
             'Panama',
             'Papua New Guinea',
             'Paraguay',
             'Peru',
             'Philippines',
             'Poland',
             'Portugal',
             'Qatar',
             'Romania',
             'Russian Federation',
             'Rwanda',
             'St Kitts & Nevis',
             'St Lucia',
             'Saint Vincent & the Grenadines',
             'Samoa',
             'San Marino',
             'Sao Tome & Principe',
             'Saudi Arabia',
             'Senegal',
             'Serbia',
             'Seychelles',
             'Sierra Leone',
             'Singapore',
             'Slovakia',
             'Slovenia',
             'Solomon Islands',
             'Somalia',
             'South Africa',
             'South Sudan',
             'Spain',
             'Sri Lanka',
             'Sudan',
             'Suriname',
             'Swaziland',
             'Sweden',
             'Switzerland',
             'Syria',]

country_code = {'afghanistan': 'AFG',
                'albania': 'ALB',
                'algeria': 'DZA',
                'andorra': 'AND',
                'angola': 'AGO',
                'antigua & deps': 'ATG',
                'argentina': 'ARG',
                'armenia': 'ARM',
                'australia': 'AUS',
                'austria': 'AUT',
                'azerbaijan': 'AZE',
                'bahamas': 'BHS',
                'bahrain': 'BHR',
                'bangladesh': 'BGD',
                'barbados': 'BRB',
                'belarus': 'BLR',
                'belgium': 'BEL',
                'belize': 'BLZ',
                'benin': 'BEN',
                'bhutan': 'BTN',
                'bolivia': 'BOL',
                'bosnia herzegovina': 'BIH',
                'botswana': 'BWA',
                'brazil': 'BRA',
                'brunei': 'BRN',
                'bulgaria': 'BGR',
                'burkina': 'BFA',
                'burundi': 'BDI',
                'cambodia': 'KHM',
                'cameroon': 'CMR',
                'canada': 'CAN',
                'cape verde': 'CPV',
                'central african rep': 'CAF',
                'chad': 'TCD',
                'chile': 'CHL',
                'china': 'CHN',
                'colombia': 'COL',
                'comoros': 'COM',
                'congo': 'COG',
                'congo {democratic rep}': 'COD',
                'costa rica': 'CRI',
                'croatia': 'HRV',
                'cuba': 'CUB',
                'cyprus': 'CYP',
                'czech republic': 'CZE',
                'denmark': 'DNK',
                'djibouti': 'DJI',
                'dominica': 'DMA',
                'dominican republic': 'DOM',
                'east timor': 'TLS',
                'ecuador': 'ECU',
                'egypt': 'EGY',
                'el salvador': 'SLV',
                'equatorial guinea': 'GNQ',
                'eritrea': 'ERI',
                'estonia': 'EST',
                'ethiopia': 'ETH',
                'fiji': 'FJI',
                'finland': 'FIN',
                'france': 'FRA',
                'gabon': 'GAB',
                'gambia': 'GMB',
                'georgia': 'GEO',
                'germany': 'DEU',
                'ghana': 'GHA',
                'greece': 'GRC',
                'grenada': 'GRD',
                'guatemala': 'GTM',
                'guinea': 'GIN',
                'guinea-bissau': 'GNB',
                'guyana': 'GUY',
                'haiti': 'HTI',
                'honduras': 'HND',
                'hungary': 'HUN',
                'iceland': 'ISL',
                'india': 'IND',
                'indonesia': 'IDN',
                'iran': 'IRN',
                'iraq': 'IRQ',
                'ireland {republic}': 'IRL',
                'israel': 'ISR',
                'italy': 'ITA',
                'ivory coast': 'CIV',
                'jamaica': 'JAM',
                'japan': 'JPN',
                'jordan': 'JOR',
                'kazakhstan': 'KAZ',
                'kenya': 'KEN',
                'kiribati': 'KIR',
                'korea north': 'PRK',
                'korea south': 'KOR',
                'kosovo': 'NONE',
                'kuwait': 'KWT',
                'kyrgyzstan': 'KGZ',
                'laos': 'LAO',
                'latvia': 'LVA',
                'lebanon': 'LBN',
                'lesotho': 'LSO',
                'liberia': 'LBR',
                'libya': 'LBY',
                'liechtenstein': 'LIE',
                'lithuania': 'LTU',
                'luxembourg': 'LUX',
                'macedonia': 'MKD',
                'madagascar': 'MDG',
                'malawi': 'MWI',
                'malaysia': 'MYS',
                'maldives': 'MDV',
                'mali': 'MLI',
                'malta': 'MLT',
                'marshall islands': 'MHL',
                'mauritania': 'MRT',
                'mauritius': 'MUS',
                'mexico': 'MEX',
                'micronesia': 'FSM',
                'moldova': 'MDA',
                'monaco': 'MCO',
                'mongolia': 'MNG',
                'montenegro': 'MNE',
                'morocco': 'MAR',
                'mozambique': 'MOZ',
                'myanmar, {burma}': 'MMR',
                'namibia': 'NAM',
                'nauru': 'NRU',
                'nepal': 'NPL',
                'netherlands': 'NLD',
                'new zealand': 'NZL',
                'nicaragua': 'NIC',
                'niger': 'NER',
                'nigeria': 'NGA',
                'norway': 'NOR',
                'oman': 'OMN',
                'pakistan': 'PAK',
                'palau': 'PLW',
                'panama': 'PAN',
                'papua new guinea': 'PNG',
                'paraguay': 'PRY',
                'peru': 'PER',
                'philippines': 'PHL',
                'poland': 'POL',
                'portugal': 'PRT',
                'qatar': 'QAT',
                'romania': 'ROU',
                'russian federation': 'RUS',
                'rwanda': 'RWA',
                'st kitts & nevis': '',
                'st lucia': '',
                'saint vincent & the grenadines': 'VCT',
                'samoa': 'ica',
                'san marino': 'SMR',
                'sao tome & principe': 'STP',
                'saudi arabia': 'SAU',
                'senegal': 'SEN',
                'serbia': 'SRB',
                'seychelles': 'SYC',
                'sierra leone': 'SLE',
                'singapore': 'SGP',
                'slovakia': 'SVK',
                'slovenia': 'SVN',
                'solomon islands': 'SLB',
                'somalia': 'SOM',
                'south africa': 'ZAF',
                'south sudan': 'SDN',
                'spain': 'ESP',
                'sri lanka': 'LKA',
                'sudan': 'SDN',
                'suriname': 'SUR',
                'swaziland': 'CHE',
                'sweden': 'SWE',
                'switzerland': 'CHE',
                'syria': 'SYR',
                'taiwan': 'TWN',
                'tajikistan': 'TJK',
                'tanzania': 'TZA',
                'thailand': 'THA',
                'togo': 'TGO',
                'tonga': 'TON',
                'trinidad & tobago': 'TTO',
                'tunisia': 'TUN',
                'turkey': 'TUR',
                'turkmenistan': 'TKM',
                'tuvalu': 'TUV',
                'uganda': 'UGA',
                'ukraine': 'UKR',
                'united arab emirates': 'ARE',
                'united kingdom': 'GBR',
                'united states': 'USA',
                'uruguay': 'URY',
                'uzbekistan': 'UZB',
                'vanuatu': 'VUT',
                'vatican city': 'VAT',
                'venezuela': 'VEN',
                'vietnam': 'VNM',
                'yemen': 'YEM',
                'zambia': 'ZMB',
                'zimbabwe': 'ZWE'}
